### ISSUE TITLE
Can't use commands, irc to steam doesn't work, and bot crashes after a variable length of time

### ISSUE THREAD

**Issue by Forblaze** [seishun/irc-steam-relay#10]
Using npm version 1.4.28, node version 0.10.32,  irc-steam-relay version 0.0.7, node-steam version 0.6.6, ursa version 0.8.0, and node-irc version 0.3.7.

I'm not sure if I actually set it up right, but here's my (edited) servers.js file:

var relay = require('irc-steam-relay');
relay({
  username: 'name',
  password: 'password',
  chatroom: 'chatid',
  server: 'irc.snoonet.org',
  port: '6667',
  nick: 'nick',
  channel: 'channel',
 
  msgFormat: '<%s> %s',
  msgFormatGame: '<%s> %s',
  emoteFormat: '<%s> %s',
  emoteFormatGame: '<%s> %s'
});

I then start it with "npm start irc-steam-relay" and just let it run from there.

The bot will run from anywhere from an hour to around a day, and then crash with this message: 

/home/pi/node_modules/irc-steam-relay/index.js:131
    var permissions = steam.chatRooms[chatRoom][chatter].permissions;
                                                        ^
TypeError: Cannot read property 'permissions' of undefined
    at SteamClient.<anonymous> (/home/pi/node_modules/irc-steam-relay/index.js:131:57)
    at SteamClient.emit (events.js:106:17)
    at SteamClient.handlers.(anonymous function) (/home/pi/node_modules/steam/lib/handlers/friends.js:203:8)
    at SteamClient._netMsgReceived (/home/pi/node_modules/steam/lib/steam_client.js:102:26)
    at SteamClient.handlers.(anonymous function) (/home/pi/node_modules/steam/lib/steam_client.js:188:10)
    at SteamClient._netMsgReceived (/home/pi/node_modules/steam/lib/steam_client.js:102:26)
    at Connection.emit (events.js:95:17)
    at Connection._readPacket (/home/pi/node_modules/steam/lib/connection.js:50:8)
    at Connection.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)

The bot has moderator (silver star) permissions, which do not include kick or ban, and is not op'd on the IRC. The .userlist command does not work on either side, even though I don't think it should require any permissions. The bot will not relay messages from IRC to Steam, but does Steam to IRC perfectly fine.

**Comment by doged** [comment]
@dinsdalepiranha sounds like you just need to change nodejs to node for your version of npm.

**Comment by doged** [comment]
also make sure its version 12 not 10

**Comment by doged** [comment]
@dinsdalepiranha yeah thats definitely your issue, you need to upgrade to 0.12.

**Comment by seishun** [comment]
I no longer maintain this project.
